export const PROTOCOL_VERSION = 1 as const;

export const REASON_CODES = [
  "PYTHON_NOT_FOUND",
  "PYTHON_VERSION_UNSUPPORTED",
  "WORKSPACE_UNTRUSTED",
  "INVALID_CONFIGURATION",
  "DOCUMENT_PARSE_FAILED",
  "NO_SQL_CANDIDATE",
  "UNSUPPORTED_LITERAL",
  "UNSAFE_FSTRING_RESTORE",
  "UNSAFE_RAW_STRING",
  "FORMATTER_FAILED",
  "RESOURCE_LIMIT_EXCEEDED",
  "PROCESS_TIMEOUT",
  "PROCESS_CANCELLED",
  "PROCESS_FAILED",
  "DOCUMENT_CHANGED",
  "APPLY_EDIT_FAILED",
  "PROTOCOL_ERROR",
] as const;
